[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  # Set this in Netlify UI or here with your backend URL
  VITE_API_BASE_URL = "https://api.foxrun.example.com"

# Optional: add redirects if needed later
# [[redirects]]
#   from = "/api/*"
#   to = "https://api.foxrun.example.com/:splat"
#   status = 200

